---

- name: Create the postgres_exporter group
  group:
    name: "{{ postgres_exporter_group }}"
    state: present
    system: true

- name: Create the postgres_exporter user
  user:
    name: "{{ postgres_exporter_user }}"
    group: "{{ postgres_exporter_group }}"
    shell: /usr/sbin/nologin
    system: true
    createhome: false
    home: "{{ postgres_exporter_root_dir }}"

- name: create postgres_exporter directories
  file:
    path: "{{ postgres_exporter_root_dir }}"
    state: directory
    owner: "{{ postgres_exporter_user }}"
    group: "{{ postgres_exporter_group }}"
    mode: 0750

- name: check if installed
  stat:
    path: "{{ postgres_exporter_root_dir }}/releases/{{ postgres_exporter_version }}/postgres_exporter"
  register: postgres_exporter_bin

- name: initialize the deploy root and gather facts
  deploy_helper:
    path: "{{ postgres_exporter_root_dir }}"
    release: "{{ postgres_exporter_version }}"
    shared_path: "{{ postgres_exporter_shared_dir }}"
    state: present

- name: create release directory
  file:
    dest: "{{ deploy_helper.new_release_path }}"
    state: directory
    owner: "{{ postgres_exporter_user }}"
    group: "{{ postgres_exporter_group }}"
    mode: 0755

- block:

    - name: create temporary deploy dir
      file:
        path: "{{ postgres_exporter_root_dir }}/tmp"
        state: directory

    - name: download archive to temporary folder
      get_url:
        url: "{{ postgres_exporter_download_url }}"
        dest: "{{ postgres_exporter_root_dir }}/tmp/{{ postgres_exporter_archive_name }}"
        remote_src: true
      register: _download_archive
      until: _download_archive is succeeded
      retries: 5
      delay: 2

    - name: unpack binaries
      unarchive:
        src: "{{ postgres_exporter_root_dir }}/tmp/{{ postgres_exporter_archive_name }}"
        dest: "{{ deploy_helper.new_release_path }}"
        remote_src: yes
        creates: "{{ deploy_helper.new_release_path }}/postgres_exporter"
        extra_opts: [--strip-components=1]
        owner: "{{ postgres_exporter_user }}"
        group: "{{ postgres_exporter_group }}"
        mode: 0755

  when: not postgres_exporter_bin.stat.exists or postgres_exporter_force_install|bool

- name: create file with env variables
  template:
    src: envs.j2
    dest: "{{ deploy_helper.shared_path }}/envs"
    owner: "{{ postgres_exporter_user }}"
    group: "{{ postgres_exporter_group }}"
    mode: 0600
  notify:
    - restart postgres_exporter

- name: copy file with extended metrics
  copy:
    src: "{{ postgres_exporter_extend_queries_filename }}"
    dest: "{{ deploy_helper.shared_path }}/queries.yaml"
    owner: "{{ postgres_exporter_user }}"
    group: "{{ postgres_exporter_group }}"
    backup: yes
    mode: 0600
  when: postgres_exporter_extend_queries_use|bool
  notify:
    - restart postgres_exporter

- name: create systemd service unit
  template:
    src: postgres_exporter.service.j2
    dest: /etc/systemd/system/postgres_exporter.service
    owner: root
    group: root
    mode: 0644
  notify:
    - restart postgres_exporter

- name: finalize the deploy, removing the unfinished file and switching the symlink
  deploy_helper:
    path: "{{ postgres_exporter_root_dir }}"
    release: "{{ deploy_helper.new_release }}"
    state: finalize
  notify:
    - restart postgres_exporter
